ID_GRAPH = "graph_petrinet"
ID_SIDE_BAR = "sidebar-card"
ID_TOAST = "id-toast"
ID_SCREENSHOT = "id-screenshot"
ID_PROPERTIES = "id-properties"
ID_APP_CONTENT = "app-content"

STORE_STARTED_NODE = "store-started-node"
STORE_SOCKET_STARTED_NODE = "store-socket-started-node"
STORE_PREV_SOCKET_STARTED_NODE = "prev-store-socket-started-node"
STORE_CURRENT_ASSERTIONS_INPUT = "store-current-assertions-input"
STORE_CURRENT_ASSERTION_INDEX = "store-current-assertion-index"
STORE_ASSERTIONS = "store-current-assertions"
STORE_UUID_FILES = "store-uuid-files"
