<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Log out_fa fa-globe-americas</name>
   <tag></tag>
   <elementGuidId>c5988ea7-ff0a-4183-8176-2292552d74c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='ossn-notif-notification']/a/span/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-globe-americas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-globe-americas</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ossn-notif-notification&quot;)/a[@class=&quot;ossn-notifications-notification&quot;]/span[1]/div[@class=&quot;ossn-icon ossn-icons-topbar-notifications-new&quot;]/i[@class=&quot;fa fa-globe-americas&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='ossn-notif-notification']/a/span/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/span/div/i</value>
   </webElementXpaths>
</WebElementEntity>
