<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_user1 text admin1_fa fa-ellipsis-h_1</name>
   <tag></tag>
   <elementGuidId>0a29f8e4-5cb7-45dc-b227-97b1afb3abdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='message-item-9']/div/div/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-ellipsis-h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-ellipsis-h</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;message-item-9&quot;)/div[@class=&quot;col-md-12 pull-right&quot;]/div[@class=&quot;message-box-sent text&quot;]/a[@class=&quot;ossn-message-delete&quot;]/i[@class=&quot;fa fa-ellipsis-h&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='message-item-9']/div/div/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/i</value>
   </webElementXpaths>
</WebElementEntity>
